# Generated by Django 5.0.4 on 2024-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sklepu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_category', models.JSONField()),
                ('product_photos', models.ImageField(upload_to='')),
                ('product_price_netto', models.FloatField()),
                ('product_price_brutto', models.FloatField()),
            ],
        ),
    ]
