# Generated by Django 5.0.4 on 2024-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_sklepu', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField()),
                ('subcategories', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='products',
            name='product_altname',
            field=models.CharField(default='altname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_subcategory',
            field=models.JSONField(default='subcategory'),
            preserve_default=False,
        ),
    ]
